first draft of whatsnew 2.0
Pylons/pyramid pull request #3565
Opened 2020-02-28 03:57 UTC by mmerickel

2020-02-28 07:22 UTC, stevepiercy commented on src/pyramid/config/security.py
> +            See :ref:`upgrading_auth_20` for more information.
```suggestion
            See :ref:`upgrading_auth` for more information.
```

There is no target `upgrading_auth_20`, but `upgrading_auth` is used. Perhaps we should be explicit about the version number throughout both the source and docs and append `_20`?

2020-11-29 05:06 UTC, mmerickel commented
Ok I added a link above to the rendered docs with a lot of changes to the docs on upgrading (ping @luhn @merwok). This is ready for review. I plan to do an alpha tomorrow and then another release once @luhn and I sort out the cookiecutter test fixtures and get that merged.

2020-11-29 08:45 UTC, stevepiercy requested changes
A couple minor edits. Excellent work.

2020-11-29 08:45 UTC, stevepiercy commented on docs/glossary.rst
> +     Setuptools / python packaging terminology.  A file representing an
```suggestion
     Setuptools / Python packaging terminology.  A file representing an
```

2020-11-29 08:45 UTC, stevepiercy commented on CHANGES.rst
>    See https://github.com/Pylons/pyramid/issue/3622
The URL is plural for issues.

```suggestion
  See https://github.com/Pylons/pyramid/issues/3622
```

2020-11-29 19:47 UTC, stevepiercy approved these changes
The additional note is a good touch, especially for those who have not been watching the changes in the last year.

2020-11-29 21:24 UTC, merged