Rename `ISecurityPolicy.authenticated_identity` to `identity`
Pylons/pyramid pull request #3620
Opened 2020-10-14 06:12 UTC by luhn

Fixes #3611

2020-10-14 19:01 UTC, bertjwregeer reviewed
This is great, thank you @luhn! Just a small change to the wording for the documentation of `identity`, maybe have @stevepiercy take a look at it too.

2020-10-14 22:55 UTC, stevepiercy approved these changes

2020-10-14 23:05 UTC, stevepiercy commented on src/pyramid/interfaces.py
>          The object's class and meaning is defined by the security policy."""
If I understand the attribute correctly, I'd suggest the following, plucking a bit from `class ISecurityPolicy(Interface)`.

```
""" An object representing the current request of the user, as determined by the security policy in use. The object's class and meaning is defined by the security policy. """
```

I would ultimately defer to @mmerickel on the most accurate and descriptive wording.

2020-10-14 23:12 UTC, mmerickel requested changes

2020-10-14 23:12 UTC, mmerickel commented on src/pyramid/interfaces.py
>          The object's class and meaning is defined by the security policy."""
> An object containing authentication information related to the current request. The object's type and meaning is defined by the configured security policy.

2020-10-14 23:31 UTC, luhn commented
Updated docstring as requested.

2020-11-02 00:15 UTC, mmerickel approved these changes

2020-11-02 00:15 UTC, merged

2020-11-02 00:16 UTC, mmerickel commented
thanks @luhn!

2020-11-02 05:02 UTC, bertjwregeer commented
\o/