Break reference cycle between request and context.
Pylons/pyramid pull request #3649
Opened 2021-01-15 19:04 UTC by luhn

When implementing traversal, it's common (at least for me) to store the request in the resource objects so you can do things like database lookups.

```python
class MyResource:
    def __init__(self, request):
        self.request = request

    def __getitem__(self, key):
        if self.request.db.lookup(key):
            return ChildResource(self.request, key)
        else:
            raise KeyError()
```

I realized this morning that this will cause a reference cycle between `request.context` and `context.request`.  Not the end of the world, obviously, but unnecessary pressure on the GC.

Maybe this is the user's responsibility?  We could document not to store the request in the context, or to use a WeakRef.

The framework can also prevent this by breaking the cycle once the request has been processed, which is what this PR does.  Really it's just a single line (`request.__dict__.pop('context', None)`), but it got a bit more complicated than that because several router tests rely on the context object being in the request.

2021-01-15 19:19 UTC, mmerickel commented on src/pyramid/router.py
> +        request.__dict__.pop('context', None)
please add a comment about breaking the cycle

2021-01-15 19:25 UTC, mmerickel commented
LGTM, do you mind updating the changelog?

2021-01-15 19:29 UTC, luhn commented
Done.  I'll also backport to 1.10.

2021-01-15 19:30 UTC, mmerickel approved these changes

2021-01-15 19:53 UTC, stevepiercy requested changes
Minor reST syntax fix.

2021-01-15 19:53 UTC, stevepiercy commented on CHANGES.rst
> +- Break potential reference cycle between `request` and `context`.
reST literals must be double-ticked.

```suggestion
- Break potential reference cycle between ``request`` and ``context``.
```

2021-01-20 00:57 UTC, luhn commented
Anything more that needs to happen on this before merge?

@stevepiercy, I made the requested rst changes.

2021-01-20 00:59 UTC, mmerickel commented
It's ready once @stevepiercy releases it.

2021-01-20 02:16 UTC, stevepiercy approved these changes
Sorry, I must have missed the GitHub notification of a pushed commit.

2021-01-20 06:45 UTC, merged