Backport to 1.10: fix imp deprecation
Pylons/pyramid pull request #3659
Opened 2021-02-24 14:55 UTC by leorochael

This is affecting the 1.10 branch today.

2021-02-24 21:18 UTC, stevepiercy requested changes
The lint build failed due to an extra space

2021-02-24 21:18 UTC, stevepiercy commented on src/pyramid/path.py
> +        _suffix for _suffix, _, _type  in imp.get_suffixes()
Fixing lint.
```suggestion
        _suffix for _suffix, _, _type in imp.get_suffixes()
```

2021-02-24 21:21 UTC, stevepiercy commented
@leorochael would you please sign [CONTRIBUTORS.txt](https://github.com/Pylons/pyramid/blob/1.10-branch/CONTRIBUTORS.txt), and push that commit? Thank you!

2021-02-25 16:35 UTC, leorochael commented
> @leorochael would you please sign [CONTRIBUTORS.txt](https://github.com/Pylons/pyramid/blob/1.10-branch/CONTRIBUTORS.txt), and push that commit? Thank you!

I was hoping not to have to do that since at first I just backported @mmerickel's commit to another branch.

But I guess I added enough new code to be able to stradle old and new Python versions, so I'll add myself.

2021-02-26 00:00 UTC, stevepiercy approved these changes
Thank you!

2021-02-26 14:07 UTC, leorochael commented
@stevepiercy, thank you for your review and approval.

What are the next steps for inclusion and new point release of the 1.10 branch?

2021-02-26 14:16 UTC, stevepiercy commented
@mmerickel is release manager, and he should review this PR, too.

Assuming he approves, he mentioned last weekend that a Pyramid 2.0 final release would come within a week. I assume he will conduct a release party soon in which the 1.10-branch will be a celebrated honoree.

2021-02-26 17:30 UTC, mmerickel commented
@leorochael LGTM - Could you please add a changelog entry for this bugfix? Thank you!

2021-03-01 02:37 UTC, merged

2021-03-01 02:56 UTC, leorochael commented
@mmerickel, sorry I couldn't get to it this weekend.

Thanks for merging and adding the changelog!

2021-03-01 02:56 UTC, mmerickel commented
No worries, I just ask out of laziness. :-) Thanks for the PR!